name: second_hand
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^3.8.0
  firebase_analytics: ^9.3.4
  firebase_core: ^1.22.0
  google_sign_in: ^5.4.2

  #  Cache
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.4.7
  shared_preferences: ^2.0.15

  # State Management
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  provider: ^6.0.3

  # Localization
  easy_localization: ^3.0.1

  # Storage
  firebase_storage: ^10.3.9
  flutter_native_image: ^0.0.6 # COMPRESS
  image_picker: ^0.8.5+3 # bunun önüne katman yazmadın

  # very_good
  very_good_analysis: ^3.1.0

  # UI
  shimmer: ^2.0.0

  equatable: ^2.0.5
  uuid: ^3.0.6
  lottie: ^1.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/animations/
