// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALHzRAZ8P9_f5eoTKEKabRstekbBIWNUA',
    appId: '1:1054331391506:web:e2c3c8d82e247d3e5552cb',
    messagingSenderId: '1054331391506',
    projectId: 'second-hand-sky',
    authDomain: 'second-hand-sky.firebaseapp.com',
    storageBucket: 'second-hand-sky.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZWO7ZxWYrchjABcAQo5DBsCfGJwpeaQ',
    appId: '1:1054331391506:android:3ab4663a5a0369255552cb',
    messagingSenderId: '1054331391506',
    projectId: 'second-hand-sky',
    storageBucket: 'second-hand-sky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOjZ2uERvadomtOI9B5Q27NEsG_7_aHa4',
    appId: '1:1054331391506:ios:ebf41b36c6a4935c5552cb',
    messagingSenderId: '1054331391506',
    projectId: 'second-hand-sky',
    storageBucket: 'second-hand-sky.appspot.com',
    iosClientId: '1054331391506-le1kkhld3j9g8bufha71jnistqpluj08.apps.googleusercontent.com',
    iosBundleId: 'sky.sky.secondHand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOjZ2uERvadomtOI9B5Q27NEsG_7_aHa4',
    appId: '1:1054331391506:ios:ebf41b36c6a4935c5552cb',
    messagingSenderId: '1054331391506',
    projectId: 'second-hand-sky',
    storageBucket: 'second-hand-sky.appspot.com',
    iosClientId: '1054331391506-le1kkhld3j9g8bufha71jnistqpluj08.apps.googleusercontent.com',
    iosBundleId: 'sky.sky.secondHand',
  );
}
